### ISSUE TITLE
Error in running example code?

### ISSUE THREAD

**Issue by akbari59** [xeniaqian94/RLeToR#1]
Thanks for sharing the code. I tried to run an experiment for TD2003 and I got the following error. 

`Error to read ../data/TD2003/Fold1/trainingset.txt.episode.pred at line 26081.
Traceback (most recent call last):
  File "reinforce.py", line 333, in <module>
    MDP_for_gradient(model, input_unsorted, output_unsorted)
  File "reinforce.py", line 275, in MDP_for_gradient
    reward, log_pi = sample_episode(model, input_unsorted, output_unsorted)
  File "reinforce.py", line 264, in sample_episode
    args.training_set + ".episode.eval")
  File "reinforce.py", line 196, in eval_reward
    with open(evalpath_this, "r") as eval_f:
IOError: [Errno 2] No such file or directory: '../data/TD2003/Fold1/trainingset.txt.episode.eval'
`

Do you have any idea what is the problem? Why the file "trainingset.txt.episode.eval" is not available?
Thanks

**Comment by xeniaqian94** [comment]
Hi @akbari59 , thanks for reusing the code. Files under `data/` were not committed in this repo because they are larger than allowed file size. It's been a while since I wrote the code. Seems the missing file is one of the intermediate output files, instead of the raw input. 

For TD2003 raw input, you could try to download from the official release of [LETOR3.0](https://www.microsoft.com/en-us/research/project/letor-learning-rank-information-retrieval/#!letor-3-0) and read data locally. IIRC, the official release divided the data into 5-folds. Hope it will help.

**Comment by akbari59** [comment]
I have already downloaded the dataset and set the correct path in the reinforce.py. The problem is from a file that store the prediction values. let me trace it and I will contact you. This is the full output log. 

`29 tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
Error to read ../data/TD2003/Fold1/trainingset.txt.episode.pred at line 26081.
Traceback (most recent call last):
  File "reinforce.py", line 333, in <module>
    MDP_for_gradient(model, input_unsorted, output_unsorted)
  File "reinforce.py", line 275, in MDP_for_gradient
    reward, log_pi = sample_episode(model, input_unsorted, output_unsorted)
  File "reinforce.py", line 264, in sample_episode
    args.training_set + ".episode.eval")
  File "reinforce.py", line 196, in eval_reward
    with open(evalpath_this, "r") as eval_f:
IOError: [Errno 2] No such file or directory: '../data/TD2003/Fold1/trainingset.txt.episode.eval'`
